# Generated by Django 3.0.7 on 2021-07-06 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_delete_emailconfirmation'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='pass_updated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teacher',
            name='pass_updated',
            field=models.BooleanField(default=False),
        ),
    ]
