# Generated by Django 2.2.7 on 2022-02-08 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='chairman',
            field=models.BooleanField(default=False),
        ),
    ]
