# Generated by Django 2.2.7 on 2022-02-08 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_teacher_chairman'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='pass_updated',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='pass_updated',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='pass_updated',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
