# Generated by Django 2.2.7 on 2022-02-08 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20220208_1155'),
    ]

    operations = [
        migrations.CreateModel(
            name='students',
            fields=[
                ('studentprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.StudentProfile')),
            ],
            bases=('account.studentprofile',),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='pass_updated',
            field=models.BooleanField(default=False),
        ),
    ]
