# Generated by Django 2.2.7 on 2022-02-08 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_auto_20220208_1201'),
    ]

    operations = [
        migrations.DeleteModel(
            name='students',
        ),
    ]
