# Generated by Django 2.2.7 on 2022-02-08 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_reviewdetails_given'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewdetails',
            name='given',
        ),
    ]
